version: "3.7"

services:
    rabbit:
        image: rabbitmq:3-management-alpine
        container_name: "rabbitmq"
        ports:
            - 5672:5672
            - 15672:15672
        hostname: rabbit
        volumes:
            - ./rabbitmq/advanced.config:/etc/rabbitmq/advanced.config
        networks:
            - rabbit_net
        restart: on-failure
    server:
        build: server/
        command: python ./consumer.py
        depends_on:
            - rabbit
            - bot
        environment:
            AMQP_URL: 'amqp://guest:guest@rabbit:5672/?name=Server%20connection'
        restart: on-failure
        networks:
            - rabbit_net
    bot:
        build: bot/
        command: python ./bot.py
        environment:
            AMQP_URL: 'amqp://guest:guest@rabbit:5672/?name=Bot%20connection'
            TOKEN: '5822952565:AAH9tX6qJUJYAtN8RjlntQ1gIyrPxD0vTFo'
        depends_on:
            - rabbit
        networks:
            - rabbit_net
        restart: on-failure
networks:
    rabbit_net:
        driver: bridge
